name: Docker CI

on:
  push:
    branches: 
      - main

jobs:
  push_to_docker_hub:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
    
    - name: Build and push Docker images  
      uses: docker/build-push-action@v6.9.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          paulo123k/meu_fastapi_app:v1
          paulo123k/meu_fastapi_app:latest