name: Docker CI

on:
  push:
    branches: 
      - main

jobs:
  push_to_docker_hub:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
    
    - name: Build and push Docker images  
      uses: docker/build-push-action@v6.9.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          paulo123k/meu_fastapi_app:${{ github.run_number }}
          paulo123k/meu_fastapi_app:latest

    - name: Install Trivy
      run: |
        sudo apt-get update -y
        sudo apt-get install -y wget
        wget https://github.com/aquasecurity/trivy/releases/download/v0.44.0/trivy_0.44.0_Linux-64bit.deb
        sudo dpkg -i trivy_0.44.0_Linux-64bit.deb
        sudo ln -s /usr/local/bin/trivy /usr/bin/trivy

    - name: Verify Trivy installation
      run: trivy --version

    - name: Scan Docker Image
      run: |
        trivy image paulo123k/meu_fastapi_app:${{ github.run_number }}
